### ISSUE TITLE
pool config

### ISSUE THREAD

**Issue by mineventure** [TheSuperiorCoin/TheSuperiorCoin#5]
http://sup.mineventure.org

Be tested on superior coin pool.
but, I need some help with something I can't.
1. home - last reward 530.8762sup --> 0.0531sup
2. Where should the market segment be revised?
3. Block found but comes out to decimal place. .... 0.052842..... sup
I need your help. Fighting SUP!!!

**Comment by mineventure** [comment]
I've got 1, 3 ...... thank you

**Comment by mps01k** [comment]
Great
